---
- name: Change ownership of homeassistant directories to {{ ha_user }}
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"
    recurse: true
  with_items:
    - "{{ ha_conf_dir }}"
    - "{{ ha_work_dir }}"
    - "{{ ha_log_dir }}"
