---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"
    recurse: true
  with_items:
    - "{{ ha_conf_dir }}"
    - "{{ ha_work_dir }}"
    - "{{ ha_log_dir }}"
