---
- name: Install required python modules (pre-install in virtual environment)
  ansible.builtin.pip:
    name:
      - colorlog
      - wheel
      - appdirs
      - packaging
      - aiohttp_cors
    virtualenv: "{{ ha_conf_dir }}"
    virtualenv_site_packages: 1
    virtualenv_command: "{{ py_which_out }} -m venv"

- name: Install Homeassistant in virtual environment in version {{ ha_version }}
  ansible.builtin.pip:
    name: homeassistant
    version: "{{ ha_version }}"
    virtualenv: "{{ ha_conf_dir }}"
    virtualenv_site_packages: 1
    virtualenv_command: "{{ py_which_out }} -m venv"
  notify: "Restart Home Assistant"
