---
- name: Get homeassistant facts
  ansible.builtin.import_tasks: get_ha_facts.yml
  tags:
      - homeassistant
      - get_ha_facts

- name: Install dependencies
  ansible.builtin.import_tasks: install_dependencies.yml
  tags:
      - homeassistant
      - dependencies

- name: Install specific version of python
  ansible.builtin.import_tasks: install_python.yml
  tags:
      - homeassistant
      - python

- name: Set firewall rules
  ansible.builtin.import_tasks: firewall.yml
  tags:
      - homeassistant
      - firewall

- name: Create user and dir
  ansible.builtin.import_tasks: create_user_and_groups.yml
  tags:
      - homeassistant
      - create_user

- name: Create directories
  ansible.builtin.import_tasks: create_directories.yml
  tags:
      - homeassistant
      - create_environment_directory

- name: Install homeassistant
  ansible.builtin.import_tasks: installation_homeassistant.yml
  tags:
      - homeassistant
      - installation
  when: not ha_version_update

- name: Restore from given backup file
  ansible.builtin.import_tasks: restore_from_backup.yml
  tags:
      - homeassistant
      - restore_backup
  when: ha_backup is defined

- name: Change ownership of homeassistant directory to {{ ha_user }}
  ansible.builtin.import_tasks: change_ownership.yml
  tags:
      - homeassistant
      - change_owner

- name: Create Service homeassistant service
  ansible.builtin.import_tasks: create_service.yml
  tags:
      - homeassistant
      - service

- name: Create cron entry for delete backup,after days "{{ ha_backup_delete_after_days }}"
  ansible.builtin.import_tasks: create_cron_to_delete_backups.yml
  tags:
      - homeassistant
      - cron
  when: ha_backup_cron | bool

- name: Update Homeassistant
  ansible.builtin.import_tasks: update_homeassistant.yml
  tags:
      - update_homeassistant
  when: ha_version_update | bool or ha_python_update | bool
