---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Install cron
      ansible.builtin.package:
        name: cron
        state: present
      when: ansible_os_family == "Debian"

    - name: Install gnupg2
      ansible.builtin.package:
        name: gnupg2
        state: present
      when: ansible_os_family == "Debian"
